### ISSUE TITLE
net.py L.Linear部分にて

### ISSUE THREAD

**Issue by togaras1** [togaras1/gengochi#1]
原因はnet.pyのL.Linear
データのチャンネル数を変更したときに発生する現象について、GenとDisに関してはbottom_widthとchをそれぞれ4と512に固定しているプロジェクトが多く、どこに原因があるかは要検証とりあえず動くチャンネル数にすることはできるが危険なためとりあえず今日のところはこれでcommitしておく。

以下の状態で再現
$python train.py -e 12000 -g 0
GPU: 0
\# Minibatch-size: 128
\# n_hidden: 100
\# epoch: 12000

Exception in main training loop:
Invalid operation is performed in: LinearFunction (Forward)

Expect: in_types[0].shape[1] == in_types[1].shape[1]
Actual: 8192 != 32768
Traceback (most recent call last):
  File "($$path to chainer$$)\chainer\training\trainer.py", line 306, in run
    update()
  File "($$path to chainer$$)\chainer\training\updaters\standard_updater.py", line 149, in update
    self.update_core()
  File "($$path to repo$$)\gengochi\updater.py", line 42, in update_core
    y_real = dis(x_real)
(以下省略)

**Comment by togaras1** [comment]
畳み込みニューラルネットワーク部分のチャンネル数は画像の大きさごとに変更して対応するということを覚えた
